# Dependabot will run on day 9 of each month at 03:57 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      day: 14
      timezone: "Europe/Berlin"
      cronjob: "57 3 9 * *"
    open-pull-requests-limit: 15
    assignees:
      - "patricknitsch"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 14
      timezone: "Europe/Berlin"
      cronjob: "57 3 9 * *"
    open-pull-requests-limit: 15
    assignees:
      - "patricknitsch"
